source 'http://rubygems.org'

platforms :ruby do
  gem 'sqlite3'
end

platforms :jruby do
  gem 'activerecord-jdbcsqlite3-adapter', '1.3.25'
end

gem 'rails', '~>4.2'
gem 'rspec'
gem 'rspec-rails'
gem 'rspec_candy'
gem 'rails-angular-xss', :path => '../..'
